### ISSUE TITLE
Can't verify webhook signature

### ISSUE THREAD

**Issue by Bartuz** [nylas/nylas-ruby#58]
Originally posted on [slack channel](https://nylas-chat.slack.com/archives/ruby-sdk/p1446917490000002):

When I tried to verify signature using example from [shopify guide](https://docs.shopify.com/api/webhooks/using-webhooks) (_btw. you should also provide this example in your docs. Verifying process was a bit confusing to me for the first time)_:

```
 digest  = OpenSSL::Digest::Digest.new('sha256')
 calculated_hmac = Base64.encode64(OpenSSL::HMAC.digest(digest, Rails.application.secrets.nylas['secret'], request.body.read)).strip == request.headers['X-Nylas-Signature']
=> false
```

**Comment by khamidou** [comment]
Hi @Bartuz,

Thanks for taking the time to fill a bug report. I actually fixed this bug when you reported it on slack --- the fix should be on production soon.

regards,

Karim

**Comment by Bartuz** [comment]
Oh, that's great! I'm juts curious - what was the reason of the bug?

**Comment by khamidou** [comment]
Fixed! We were passing one parameter wrong when computing the HMAC.

**Comment by Bartuz** [comment]
@khamidou still does not work for me. Can you paste code snippet with your code working?

**Comment by khamidou** [comment]
As discussed on Slack, [here's an example of how to verify the hook's signature](https://gist.github.com/khamidou/1df27edb0f7fc08d47f0).
